module.exports = {
  decodeHtmlEntities: async (input) => {
    const entities = {
      "&amp;": "&",
      "&lt;": "<",
      "&gt;": ">",
      "&quot;": '"',
      "&apos;": "'",
      "&#x27;": "'",
      "&#x60;": "`",
      "&#x2F;": "/",
      "&copy;": "©",
      "&reg;": "®",
      "&euro;": "€",
      "&pound;": "£",
      "&yen;": "¥",
      "&cent;": "¢",
      "&hellip;": "…",
      "&mdash;": "—",
      "&ndash;": "–",
      "&lsquo;": "‘",
      "&rsquo;": "’",
      "&sbquo;": "‚",
      "&ldquo;": "“",
      "&rdquo;": "”",
      "&bdquo;": "„",
      "&laquo;": "«",
      "&raquo;": "»",
      "&lsaquo;": "‹",
      "&rsaquo;": "›",
      "&trade;": "™",
      "&minus;": "−",
      "&plusmn;": "±",
      "&times;": "×",
      "&divide;": "÷",
      "&frac12;": "½",
      "&frac14;": "¼",
      "&frac34;": "¾",
      "&ordm;": "º",
      "&ordf;": "ª",
      "&sect;": "§",
      "&para;": "¶",
      "&deg;": "°",
      "&alpha;": "α",
      "&beta;": "β",
      "&gamma;": "γ",
    };
    return input.replace(/&[a-zA-Z]+;|&#[0-9]+;|&#x[0-9a-fA-F]+;/g, (match) => {
      return entities[match] || match;
    });
  },
};
